s1="abcdefg"
s2="acbdfeg"
if(len(s2)==len(s1)):
    i=0
    while(i<len(s1)):
        if(s1[i]!=s2[i]):
            s3=""
            s4=""
            s3+=s1[i]
            s4+=s2[i]
            while(s1[i+1]!=s2[i+1]):
                s3+=s1[i+1]
                s4+=s2[i+1]
                i+=1
            s3+="-"+s4
            print(s3)
        i+=1
else:
    print("Length of the both string should be equal")
